spring:
  application:
    name: HomeSweetCrawler
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_NAME}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 200
        order_inserts: true
        order_updates: true
    open-in-view: false

naver:
  api:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    base-url: https://openapi.naver.com/v1/search/shop.xml
    request-delay: 100

server:
  port: 8888